# Generated by Django 5.1.3 on 2024-12-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='name',
            new_name='title',
        ),
    ]
